name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  call-run-python-tests:
    name: Run tests

    permissions:
      contents: write
      pull_request: write

    uses: Mews/.github/.github/workflows/run-python-tests.yaml@main
    with:
      tests_dir: "tests/"
      python_versions: '["3.10", "3.13"]'
      os_list: '["ubuntu-latest", "windows-latest"]'
      create_coverage_comment: true